# load dependencies
source("generateRMR.R")
source("generateRPPR.R")

# main
# generateRMR(site = "Yale")
# generateRMR(site = "Emory")
# generateRMR(site = "NU")
# generateRMR(site = "Temple")
# generateRMR(site = "UCI")
# generateRMR(site = "UGA")
# generateRMR(site = "UMBC")

# generateRPPR()
generateRPPR(site = "Yale")
yale_df <- generateRPPR(site = "Yale")
generateRPPR(site = "Emory")
emory_df <- generateRPPR(site = "Emory")
# generateRPPR(site = "NU")
# tmp <- generateRPPR(site = "Yale")
# generateRPPR(site = "Temple")
# tmp <- generateRPPR(site = "Yale")
# generateRPPR(site = "UCI")
# tmp <- generateRPPR(site = "Yale")
# generateRPPR(site = "UGA")
# tmp <- generateRPPR(site = "Yale")
# generateRPPR(site = "UMBC")
# tmp <- generateRPPR(site = "Yale")