# load generateRMRv2()
source("generateRMRv2.R")

# run generateRMRv2()
View(generateRMR(site = "Yale"))
View(generateRMR(site = "Emory"))
View(generateRMR(site = "NU"))
View(generateRMR(site = "Temple"))
View(generateRMR(site = "UCI"))
View(generateRMR(site = "UGA"))
View(generateRMR(site = "UMBC"))